import './Home.css'

import bola from '../../images/bola.png'

export default function Home() {
    return (
        <article>
            <img className='imgHome' src={bola} alt='bola' />
            <h1>Diego Maradona</h1>
            <p><strong>Diego Armando Maradona Franco</strong> (Lanús, 30 de outubro de 1960 — Tigre, 25 de novembro de 2020) foi um treinador e futebolista argentino que atuava como meia-atacante. Considerado <strong>um dos maiores futebolistas de todos os tempos</strong>, liderou a conquista da Copa do Mundo de 1986, marcando, nas quartas de final, o Gol do Século. Ele ainda disputou mais três mundiais (1982, 1990 e 1994), tendo alcançado o vice-campeonato em 1990. A Copa de 1994 ficou marcada como o ponto final da vitoriosa trajetória de Maradona pela Seleção, após ele ser apanhado no exame antidoping na partida contra a Nigéria (a segunda da Argentina no Mundial). Por conta de sua notória participação nos mundiais, em 2002 ele foi escolhido para o <strong>Time dos Sonhos das Copas do Mundo FIFA</strong>.</p>
            <p>Amplamente considerado um dos maiores, mais famosos e mais polêmicos jogadores do século XX, diversas personalidades e organizações reconheceram-no como <strong>um dos melhores jogadores da história do futebol</strong> e dos mundiais. Na votação do Melhor Jogador do Século XX pela FIFA, realizada em dezembro de 2000, ele ficou na primeira posição da votação popular, e em terceiro na votação dos especialistas selecionados pela FIFA. Neste mesmo ano, ele foi eleito o quinto melhor jogador da história pela IFFHS.</p>
            <p>Enquanto jogador, Maradona foi reverenciado como uma <strong>divindade</strong> em seu país natal, sendo criada inclusive uma igreja dedicada a ele. Seu maior momento foi na Copa do Mundo de 1986 que, na opinião popular, foi ganha sozinha por <strong>El Pibe de Oro</strong>, outra de suas muitas alcunhas. Nesta Copa, que ficou conhecida como "<strong>A Copa do Maradona</strong>", Dieguito teve influência direta em 71% dos 14 gols anotados pela Argentina na campanha do título (ele marcou cinco tentos e deu cinco assistências para gols), sendo a maior porcentagem individual da história das Copas. Internacionalmente, Maradona também consagrou-se como herói da equipe italiana do Napoli, um clube que, embora tradicional, esteve entre os pequenos do país. Com <strong>El Diez</strong>, o Napoli viveu momentos de glória no final da década de 1980, ganhando seus dois únicos títulos no Campeonato Italiano e lutando de igual para igual com as maiores equipes do país. Além disso, Maradona foi o primeiro jogador na história do futebol a estabelecer duas vezes o recorde mundial de transferência mais cara: primeiro, quando foi transferido para o Barcelona por um recorde mundial de 5 milhões de euros, e o segundo quando foi transferido para o Napoli pelo valor recorde de 6,9 milhões de euros.</p>
            <p>A carreira de Maradona, porém, foi cercada de controvérsias, que não se limitaram aos gramados. Algumas delas estão relacionadas ao seu abuso de drogas, vício que levou ao seu banimento dos gramados por duas ocasiões, em 1991 e 1994. Teve também dois filhos fora do casamento que não reconheceu como seus. E rotineiramente fazia declarações contra os bastidores da FIFA, principalmente aos dirigentes João Havelange, Joseph Blatter, Michel Platini, Franz Beckenbauer, além de Pelé, e também tem um histórico de atritos com imprensas, incluindo a de seu próprio país. Morreu aos sessenta anos de idade, na sua residência em Tigre, vítima de uma parada cardiorrespiratória.</p>
        </article>
    )
}